-- Note: RLS is disabled for Railway PostgreSQL since the bot is the only direct client
-- In production with direct web access, these policies would need to be updated
-- to work without Supabase's auth schema

-- For now, keep RLS disabled to allow bot direct access
-- ALTER TABLE features ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE feature_permissions ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE embed_configs ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE message_data ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE pruning_config ENABLE ROW LEVEL SECURITY;